# Generated by Django 4.2.23 on 2025-08-01 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id_concepto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_concepto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('rut', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('dotacion', models.CharField(max_length=50)),
                ('area_trabajo', models.CharField(blank=True, choices=[('ANALISIS', 'Área de Análisis'), ('CONTABILIDAD', 'Área de Contabilidad'), ('PAGO', 'Área de Pago')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id_grado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_grado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MotivoPago',
            fields=[
                ('id_motivopago', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_motivo_pago', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteFuncionario',
            fields=[
                ('id_reporte_funcionario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('ncu_doe', models.IntegerField()),
                ('motivo_bloqueo', models.CharField(max_length=50)),
                ('observaciones_analisis', models.TextField(blank=True, null=True)),
                ('nro_comprobante_contable', models.CharField(blank=True, max_length=50, null=True)),
                ('observaciones_contabilidad', models.TextField(blank=True, null=True)),
                ('nro_nomina_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('observaciones_pago', models.TextField(blank=True, null=True)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes', to='valores_retenidos.concepto')),
                ('estado_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='valores_retenidos.estado')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='valores_retenidos.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SeguimientoUsuario',
            fields=[
                ('id_seguimiento_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_seguimiento', models.DateTimeField(auto_now_add=True)),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='valores_retenidos.estado')),
                ('id_reporte_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='valores_retenidos.reportefuncionario')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acciones', to='valores_retenidos.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoRemuneracion',
            fields=[
                ('id_periodo_remuneracion', models.AutoField(primary_key=True, serialize=False)),
                ('periodo_remuneracion', models.DateField()),
                ('monto', models.FloatField()),
                ('ingreso_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='valores_retenidos.reportefuncionario')),
                ('motivo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='valores_retenidos.motivopago')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='valores_retenidos.funcionario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='funcionario',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='valores_retenidos.grado'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='valores_retenidos.rol'),
        ),
    ]
