# Generated by Django 4.2.23 on 2025-08-21 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valores_retenidos', '0002_alter_funcionario_dotacion_alter_funcionario_grado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacion',
            fields=[
                ('id_aplicacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AccesoAplicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to='valores_retenidos.aplicacion')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_app', to='valores_retenidos.funcionario')),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='valores_retenidos.rol')),
            ],
            options={
                'unique_together': {('funcionario', 'aplicacion')},
            },
        ),
    ]
