# Generated by Django 5.2 on 2025-06-25 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id_concepto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_concepto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id_grado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_grado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MotivoPago',
            fields=[
                ('id_motivopago', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_motivo_pago', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('rut', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('dotacion', models.CharField(max_length=50)),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='common.grado')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteFuncionario',
            fields=[
                ('id_reporte_funcionario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('ncu_doe', models.IntegerField()),
                ('motivo_bloqueo', models.CharField(max_length=50)),
                ('observaciones', models.TextField()),
                ('nro_comprobante_contable', models.CharField(blank=True, max_length=50, null=True)),
                ('observaciones_contabilidad', models.TextField(blank=True, null=True)),
                ('nro_nomina_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('observaciones_pago', models.TextField(blank=True, null=True)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes', to='common.concepto')),
                ('estado_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.estado')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='common.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoRemuneracion',
            fields=[
                ('id_periodo_remuneracion', models.AutoField(primary_key=True, serialize=False)),
                ('periodo_remuneracion', models.DateField()),
                ('monto', models.FloatField()),
                ('motivo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.motivopago')),
                ('ingreso_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='common.reportefuncionario')),
            ],
        ),
        migrations.CreateModel(
            name='SeguimientoUsuario',
            fields=[
                ('id_seguimiento_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_seguimiento', models.DateTimeField(auto_now_add=True)),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.estado')),
                ('id_reporte_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='common.reportefuncionario')),
            ],
        ),
    ]
