# Generated by Django 5.2 on 2025-07-01 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='reportefuncionario',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='area_trabajo',
            field=models.CharField(blank=True, choices=[('ANALISIS', 'Área de Análisis'), ('CONTABILIDAD', 'Área de Contabilidad'), ('PAGO', 'Área de Pago')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reportefuncionario',
            name='observaciones_analisis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seguimientousuario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acciones', to='common.funcionario'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='common.rol'),
        ),
    ]
